In [2]:
import numpy as np

In [3]:
nda = np.array([ #create an array, takes a single argument []
    [1, 2, 3, 4],
    [2, 5, 6, 9]
], dtype = int) #giving the dtype is optional

In [4]:
nda.ndim #number of dimensions

2

In [5]:
nda.shape

(2, 4)

In [6]:
nda.size #product of shape

8

In [7]:
a = np.arange(16).reshape(4, 4) #brings an array with 16 data points into shape

In [10]:
a.itemsize

8

### Creating Arrays

In [27]:
#Creating random arrays with a specific size
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [73]:
np.empty((2, 3)) #gives random numbers

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

### Aranging Arrays

In [12]:
#Arange function
np.arange(2, 20, 4) #start with 2, stop at 20, increase by 4

array([ 2,  6, 10, 14, 18])

In [34]:
#Linspace function
np.linspace(2, 20, 9) #give me 9 numbers between 2 and 20

array([ 2.  ,  4.25,  6.5 ,  8.75, 11.  , 13.25, 15.5 , 17.75, 20.  ])

In [37]:
#Work with Pi
np.linspace(1, 2*np.pi, 10)

array([1.        , 1.58702059, 2.17404118, 2.76106177, 3.34808236,
       3.93510295, 4.52212354, 5.10914413, 5.69616472, 6.28318531])

In [14]:
#Reshape function
np.arange(12).reshape(2, 6) #reshape parameters must match total number of items

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [68]:
np.arange(12).reshape(2, 3, 2) #3d array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

### Basic Operations

In [69]:
a = np.empty((1, 4))
b = np.arange(4)

In [48]:
c = a-b
c

array([[-1.28822975e-231, -1.00000000e+000, -2.00000000e+000,
        -3.00000000e+000]])

In [50]:
np.sin(a)

array([[1.28822975e-231, 8.41470985e-001, 9.09297427e-001,
        1.41120008e-001]])

In [51]:
#The * operator does element-wise operations,
# the @ operator calculates the matrix product - dot function
A = np.empty((2, 2))
B = np.empty ((2, 2))
A * B

array([[-0.00000000e+000,  1.25764048e-154],
       [ 1.48219694e-323,  0.00000000e+000]])

In [52]:
A @ B

array([[1.35901210e-154, 2.10914265e-155],
       [0.00000000e+000, 1.48219694e-323]])

In [53]:
A.dot(B) #same result as @ 

array([[1.35901210e-154, 2.10914265e-155],
       [0.00000000e+000, 1.48219694e-323]])

In [62]:
rg = np.random.default_rng(1) #create default number generator instance
rg.random((2, 3))

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [64]:
a = rg.random((2, 3))
a

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [65]:
a.sum()

2.412007822394087

In [66]:
a.min()

0.13404169724716475

In [67]:
a.max()

0.7884287034284043

In [76]:
#If we specify the dim in the function, we can do these operations
# along a specific axis
b = rg.random((3, 4))
b

array([[0.51606859, 0.11586561, 0.62348976, 0.77668311],
       [0.6130033 , 0.9172977 , 0.03959288, 0.52858926],
       [0.45933588, 0.06234958, 0.64132817, 0.85263284]])

In [78]:
b.sum(axis = 0) #sum of each column

array([1.58840777, 1.0955129 , 1.3044108 , 2.15790522])

In [82]:
b.sum(axis = 1) #sum of each row

array([2.03210707, 2.09848315, 2.01564647])

In [83]:
b.cumsum(axis = 1) #cumulative sum of each row

array([[0.51606859, 0.6319342 , 1.25542395, 2.03210707],
       [0.6130033 , 1.53030101, 1.56989388, 2.09848315],
       [0.45933588, 0.52168546, 1.16301363, 2.01564647]])

### Universal Functions

In [85]:
#Many mathematical functions, those operate elementwise
# and therefore produce an array as output
b = rg.random(3)
b

array([0.50949588, 0.51088888, 0.75303021])

In [86]:
np.exp(b)

array([1.6644519, 1.6667721, 2.1234247])

In [87]:
np.sqrt(b)

array([0.7137898 , 0.71476492, 0.86777313])

In [ ]:
#and many more: argmin, dot, max, mean, median, ...

### Indexing, Slicing and Iterating

#### One-dimensional

In [94]:
a = rg.random(5)
a

array([0.8765371 , 0.47190972, 0.27404839, 0.00709183, 0.6457209 ])

In [95]:
a[2:4] #last index is not included

array([0.27404839, 0.00709183])

In [98]:
a[1:5:2] = 1 #from position to position set every 2nd element to 1
a

array([0.8765371 , 1.        , 0.27404839, 1.        , 0.6457209 ])

In [99]:
a[::-1] #reverse a

array([0.6457209 , 1.        , 0.27404839, 1.        , 0.8765371 ])

In [101]:
#Looping
for i in a:
    print(i**2)

0.7683172813944098
1.0
0.07510251930177556
1.0
0.41695547498211266


#### Multi-dimensional

They have one index per axis

In [102]:
def f(x, y):
    return x+y

In [106]:
b = np.fromfunction(f, (4, 5))
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.,  6.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 6.,  7.,  8.,  9., 10.]])

In [108]:
b[2, 3]

7.0

In [109]:
b[0:5, 1] #row 0-5 from column on index 1s

array([1., 3., 5., 7.])

The dots parameter represents as many ':' as needed

In [114]:
c = rg.random((2, 2, 3)) #3D array
c

array([[[0.02449068, 0.67345989, 0.91908862],
        [0.82682533, 0.88552027, 0.66035538]],

       [[0.24555227, 0.768517  , 0.21167474],
        [0.83127483, 0.06271792, 0.82548781]]])

In [116]:
c[1, ...]

array([[0.24555227, 0.768517  , 0.21167474],
       [0.83127483, 0.06271792, 0.82548781]])

In [121]:
c[..., 2] #equivalent to c[:, :, 2]

array([[0.91908862, 0.66035538],
       [0.21167474, 0.82548781]])

Loop on every item of an array: .flat:

In [122]:
for i in c.flat:
    print(i)

0.0244906774933632
0.6734598871529389
0.9190886196338225
0.8268253295567211
0.8855202667099468
0.6603553805205233
0.24555226724317758
0.7685169988962544
0.2116747426075105
0.8312748346644612
0.06271792257076825
0.8254878133935558


### Shape Manipulation

Changing the shape of arrays

In [129]:
x = rg.random((4, 3))
x

array([[0.58651833, 0.8396846 , 0.72647361],
       [0.36500726, 0.44839631, 0.36769957],
       [0.10973466, 0.20324154, 0.28380649],
       [0.3141339 , 0.31304786, 0.57669972]])

In [138]:
x.reshape(6, -1) #the -1 gives automatic amount of columns due to the rows

array([[0.58651833, 0.8396846 ],
       [0.72647361, 0.36500726],
       [0.44839631, 0.36769957],
       [0.10973466, 0.20324154],
       [0.28380649, 0.3141339 ],
       [0.31304786, 0.57669972]])

In [132]:
x.T #transpose the array

array([[0.58651833, 0.36500726, 0.10973466, 0.3141339 ],
       [0.8396846 , 0.44839631, 0.20324154, 0.31304786],
       [0.72647361, 0.36769957, 0.28380649, 0.57669972]])

all those methods do not change the array itself, but resize does:

In [134]:
x

array([[0.58651833, 0.8396846 , 0.72647361],
       [0.36500726, 0.44839631, 0.36769957],
       [0.10973466, 0.20324154, 0.28380649],
       [0.3141339 , 0.31304786, 0.57669972]])

In [137]:
x.resize((1, 12))
x #that's why x needs to be called explicitly and resize does not
    # give output

array([[0.58651833, 0.8396846 , 0.72647361, 0.36500726, 0.44839631,
        0.36769957, 0.10973466, 0.20324154, 0.28380649, 0.3141339 ,
        0.31304786, 0.57669972]])