Descriptive Statistics and DF summarizing by the **Python for Data Analysis** Book by *Wes McKinney*

In [2]:
import numpy as np
import pandas as pd

In [49]:
df = pd.DataFrame([[1.2, np.nan], [4.1, -3.1],
                  [np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])
df

one  two
a  1.20  NaN
b  4.10 -3.1
c   NaN  NaN
d  0.75 -1.3

### Description of a DF

In [12]:
df.describe()

one       two
count  3.000000  2.000000
mean   2.016667 -2.200000
std    1.818195  1.272792
min    0.750000 -3.100000
25%    0.975000 -2.650000
50%    1.200000 -2.200000
75%    2.650000 -1.750000
max    4.100000 -1.300000

### Summary Functions

NAs are excluded unless the whole row / column is NA. This can be changed with `skipna=False`.

In [8]:
df.sum(axis = 1, skipna = False) #row-wise

a     NaN
b    1.00
c     NaN
d   -0.55
dtype: float64

`.idxmax() / .idxmin()`: return the index value of the min / max values

In [13]:
df.idxmax()

one    b
two    d
dtype: object

In [14]:
df.idxmin()

one    d
two    b
dtype: object

In [15]:
#Accumulations:
df.cumsum()

one  two
a  1.20  NaN
b  5.30 -3.1
c   NaN  NaN
d  6.05 -4.4

### Correlation and Covariance P160

In [21]:
df.corr()

one  two
one  1.0 -1.0
two -1.0  1.0

In [22]:
df.cov()

one    two
one  3.305833 -3.015
two -3.015000  1.620

Specifying a column in the corr() or cov() function results in a single corr / cov value.

`.corrwith()` computes pairwise correlations between columns or rows.

In [25]:
df.corrwith(df.two)

one   -1.0
two    1.0
dtype: float64

In [53]:
df.fillna(0).corrwith(df.one, axis =0) #axis can be specified as well

one    1.000000
two   -0.849999
dtype: float64

### Unique Values, Value Counts, Membership

In [34]:
ser = pd.Series([1, 2, 3, 4])
ser

0    1
1    2
2    3
3    4
dtype: int64

In [35]:
ser.unique() #returns all unique values

array([1, 2, 3, 4])

In [33]:
ser.value_counts() #series with value frequencies

4    1
3    1
2    1
1    1
dtype: int64

In [36]:
ser.value_counts(sort = False) #no sorting of the result

1    1
2    1
3    1
4    1
dtype: int64

In [40]:
mask = ser.isin([1, 2]) #checks whether a value / values is / are in the series
mask

0     True
1     True
2    False
3    False
dtype: bool

In [41]:
ser[mask] #returns values filtered by the mask

0    1
1    2
dtype: int64

In [45]:
pd.Index(ser).get_indexer([3, 4]) #returns index of number 3 and 4

array([2, 3])

### Filtering Missing Data: NA

In [55]:
data = pd.Series([1, np.nan, 3, 4, 5, np.nan, 7])
data

0    1.0
1    NaN
2    3.0
3    4.0
4    5.0
5    NaN
6    7.0
dtype: float64

In [56]:
data.dropna()

0    1.0
2    3.0
3    4.0
4    5.0
6    7.0
dtype: float64

In [57]:
#equivalent to:
data[data.notnull()]

0    1.0
2    3.0
3    4.0
4    5.0
6    7.0
dtype: float64

Different for DF, do you drop rows / cols with some NAs or all NAs?

In [8]:
df = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                   [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
df

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
df.isnull().sum()

0    2
1    2
2    2
dtype: int64

In [60]:
df.dropna() #drops every row with some sort of NA

0    1    2
0  1.0  6.5  3.0

In [62]:
df.dropna(how = 'all') #only rows with all NAs

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [63]:
df.dropna(how ='all', axis = 1) #drop columns with all NAs

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [68]:
df.dropna(thresh = 2) #drop rows with less than 2 valid values

0    1    2
0  1.0  6.5  3.0
3  NaN  6.5  3.0

### Filling missing data

In [72]:
df.fillna(0) #inplace = True for converting the same object

0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  6.5  3.0

In [71]:
df.fillna({0: 0.5, 1: 12, 2: 'a'}) #fill NAs with different values 
                                    # per columnn

0     1  2
0  1.0   6.5  3
1  1.0  12.0  a
2  0.5  12.0  a
3  0.5   6.5  3

In [74]:
df.fillna(method = 'ffill') #fill with previous value

0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

In [77]:
df.fillna(method = 'ffill', limit = 1) #maximum one

0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  NaN  NaN
3  NaN  6.5  3.0

In [78]:
df.fillna(df.mean()) #fill with mean of each column

0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

### Transforming Data

#### Removing Duplicates

In [18]:
df = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
df

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [19]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [80]:
df.drop_duplicates() #removes duplicates based on all columns

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [83]:
df.drop_duplicates(['k2'], keep = 'last')
#drops duplicates in the column k2 and keeps the last occurence of the 
 # duplicates

k1  k2
1  two   1
2  one   2
4  one   3
6  two   4

### Replacing Data

In [84]:
ser = pd.Series([1., -999., 2., -999., -1000., 3.])
ser

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [85]:
ser.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [86]:
ser.replace([-999, -1000], np.nan) #replace multiple values at once

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [87]:
ser.replace([-999, -1000], [np.nan, 0]) #replace with different values

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis

In [88]:
df = pd.DataFrame(np.arange(12).reshape((3, 4)),
                 index = ['Ohio', 'Colorado', 'New York'],
                 columns = ['one', 'two', 'three', 'four'])
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [97]:
transform = lambda x: x[:].upper()

In [98]:
df.index.map(transform)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

### Discretization and Binning

In [99]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [109]:
bins = [1, 18, 30, 50, 99]

In [110]:
cat_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [111]:
categories = pd.cut(ages, bins, labels = cat_names)
categories

[YoungAdult, YoungAdult, YoungAdult, YoungAdult, YoungAdult, ..., MiddleAged, Senior, MiddleAged, MiddleAged, MiddleAged]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [112]:
categories.codes

array([1, 1, 1, 1, 1, 1, 2, 2, 3, 2, 2, 2], dtype=int8)

In [113]:
categories.categories

Index(['Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [115]:
pd.value_counts(categories)

YoungAdult    6
MiddleAged    5
Senior        1
Youth         0
dtype: int64

Without passing a bin to `.cut`, equal bin sizes can be created as well.

In [120]:
pd.cut(ages, 4, precision = 0) #precision limits the decimal precision

[(20.0, 30.0], (20.0, 30.0], (20.0, 30.0], (20.0, 30.0], (20.0, 30.0], ..., (30.0, 40.0], (51.0, 61.0], (40.0, 51.0], (40.0, 51.0], (30.0, 40.0]]
Length: 12
Categories (4, interval[float64]): [(20.0, 30.0] < (30.0, 40.0] < (40.0, 51.0] < (51.0, 61.0]]

`.qcut` can be used for splitting based on quantiles. This should result in equal-size bins.

In [124]:
cats = pd.qcut(ages, 4) #split into quartiles
cats

[(19.999, 22.75], (19.999, 22.75], (22.75, 29.0], (22.75, 29.0], (19.999, 22.75], ..., (29.0, 38.0], (38.0, 61.0], (38.0, 61.0], (38.0, 61.0], (29.0, 38.0]]
Length: 12
Categories (4, interval[float64]): [(19.999, 22.75] < (22.75, 29.0] < (29.0, 38.0] < (38.0, 61.0]]

In [131]:
pd.value_counts(cats)

(38.0, 61.0]       3
(29.0, 38.0]       3
(22.75, 29.0]      3
(19.999, 22.75]    3
dtype: int64

In [129]:
#split into definied bins
pd.qcut(ages, [0, 0.7, 1])

[(19.999, 35.5], (19.999, 35.5], (19.999, 35.5], (19.999, 35.5], (19.999, 35.5], ..., (19.999, 35.5], (35.5, 61.0], (35.5, 61.0], (35.5, 61.0], (19.999, 35.5]]
Length: 12
Categories (2, interval[float64]): [(19.999, 35.5] < (35.5, 61.0]]

### Detecting and Filtering Outliers

In [135]:
df = pd.DataFrame(np.random.randn(1000, 4))
df

0         1         2         3
0    0.027461  1.281612  0.919310  0.262248
1    0.238304  1.095536  0.311289  0.566542
2    1.545578  0.606512 -0.915673  1.398102
3   -0.154768  0.164971  1.573542 -1.460252
4    0.129153  0.076504  0.967260 -1.889522
..        ...       ...       ...       ...
995 -0.153416  0.513887 -0.375931 -0.666642
996  0.889301 -1.986102 -0.910717  1.042767
997 -0.407008 -0.507819 -1.408662 -1.725516
998  0.852074 -0.463060  0.373542  1.089625
999  0.144301  0.290791  0.828149 -0.712821

[1000 rows x 4 columns]

In [144]:
np.sign(df).head() #sign produces -1 and 1 for neg / pos values

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0 -1.0  1.0
3 -1.0  1.0  1.0 -1.0
4  1.0  1.0  1.0 -1.0

### Computing Indicator / Dummy Variables P208

In [145]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [146]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [147]:
dummies = pd.get_dummies(df['key'], prefix = 'key')

In [150]:
df_w_dummy = df.join(dummies)
df_w_dummy

key  data1  key_a  key_b  key_c
0   b      0      0      1      0
1   b      1      0      1      0
2   a      2      1      0      0
3   c      3      0      0      1
4   a      4      1      0      0
5   b      5      0      1      0